mysite/ChitChat/urls.py
from django.urls import path, include
from ChitChat import views as chat_views
from django.contrib.auth.views import LoginView, LogoutView

# urlpatterns = [
#     path("", chat_views.chatPage, name="chat-page"),

#     # authentication section
#     path("auth/login/", LoginView.as_view
#          (template_name="chat/loginPage.html"), name="login-user"),
#     path("auth/login/", LogoutView.as_view(), name="logout-user"),
# ]

app_name = "chat"
urlpatterns = [
    path("", chat_views.chatPage, name="chat-page"),

    # authentication section
    path("auth/login/", LoginView.as_view
         (template_name="chat/loginPage.html", next_page="chat:chat-page"), name="login-user"),
    path("auth/logout/", LogoutView.as_view(next_page="chat:login-user"), name="logout-user"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
	path("chat/", include("ChitChat.urls")),
	path("transcendence/", include("transcendence.urls")),
]

mysite/polls/urls.py
from django.urls import path

from . import views

# app_name = "polls"
# urlpatterns = [
# 	# ex: /polls/
# 	path("", views.index, name="index"),
# 	# ex: /polls/5/
# 	path("specifics/<int:question_id>/", views.detail, name="detail"),
# 	# ex: /polls/5/results/
# 	path("<int:question_id>/results/", views.results, name="results"),
# 	# ex: /polls/5/vote/
# 	path("<int:question_id>/vote/", views.vote, name="vote"),
# ]

app_name = "polls"
urlpatterns = [
	path("", views.IndexView.as_view(), name="index"),
	path("<int:pk>/", views.DetailView.as_view(), name="detail"),
	path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
	path("<int:question_id>/vote/", views.vote, name="vote"),
]

# 이제 polls 앱의 view를 호출하기 위해 URLconf를 설정했다.
# 이 URLconf는 polls 앱의 view를 호출하기 위한 URL을 지정한다.
# 이제는 global URLconf에 이 URLconf를 포함시켜야 한다.

mysite/transcendence/urls.py
from django.urls import path, include
from transcendence import views as transcendence_views

app_name = "pingpong"
urlpatterns = [
	path("api/check-session/", transcendence_views.check_session, name="check-session"),
	path("api/user-session-history/<str:username>/", transcendence_views.MatchHistoryView.as_view(), name="user-session-history"),

	path("match/", transcendence_views.match, name="match"),
	path("pingpong/", transcendence_views.pingpong, name="pingpong"),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField("date published")
	def __str__(self):
		return self.question_text + " (" + str(self.pub_date) + ")"
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

mysite/transcendence/models.py
from django.db import models

# Create your models here.
class GameSession(models.Model):
	session_id = models.CharField(max_length=100, unique=True)
	websocket_url = models.URLField()
	websocket_port = models.IntegerField()
	is_active = models.BooleanField(default=False)
	players = models.ManyToManyField('Player', related_name='game_sessions')
	players_connected = models.ManyToManyField('Player', related_name='game_sessions_connected')

	def __str__(self):
		return f"Session {self.session_id} - Active: {self.is_active} - Players: {self.players.all()}"

class Player(models.Model):
	username = models.CharField(max_length=100, unique=True)
	score = models.IntegerField(default=0)

	def __str__(self):
		return f"Player {self.username} - Score: {self.score}"

class Match(models.Model):
	player1 = models.CharField(max_length=100, null=True, blank=True)
	player2 = models.CharField(max_length=100, null=True, blank=True)
	winner = models.CharField(max_length=100, null=True, blank=True)

	def __str__(self):
		player1_name = self.player1 if self.player1 else "Unknown"
		player2_name = self.player2 if self.player2 else "Unknown"
		return f"Match {self.id}: {player1_name} vs {player2_name}"


class SessionHistory(models.Model):
	match = models.ManyToManyField(Match, related_name='match_history')
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"SessionHistory {self.id} - Matches: {self.match.count()}"

mysite/ChitChat/views.py
from django.shortcuts import render, redirect

def chatPage(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("chat:login-user")
    context = {}
    return render(request, "chat/chatPage.html", context)

mysite/polls/views.py
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

# Create your views here.
class IndexView(generic.ListView):
	template_name = "polls/index.html"
	context_object_name = "latest_question_list"
	
	def get_queryset(self):
		"""
		Return the last five published questions (not including those set to be
		published in the future).
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = "polls/detail.html"
	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = "polls/results.html"

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST["choice"])
	except (KeyError, Choice.DoesNotExist):
		return render(request, "polls/detail.html", {
			"question": question,
			"error_message": "You didn't select a choice.",
		})
	else:
		selected_choice.votes = F("votes") + 1
		selected_choice.save()
		return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

# 브라우저에서 url을 통해 해당 view를 보려면 urls.py를 작성해야 함.

mysite/transcendence/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .models import GameSession, Match, SessionHistory
from .serializers import SessionHistorySerializer
from django.shortcuts import render

# Create your views here.
@api_view(['GET'])
def check_session(request):
	# 게임 세션 검색
	session_available = check_for_available_session()
	if session_available:
		# 세션이 있을 경우
		response_data = {
			"session_id": session_available['session_id'],
			"websocket_url": session_available['websocket_url'],
			"websocket_port": session_available['websocket_port']
		}
	else:
		# 세션이 없을 경우
		response_data = {
			"session_id": None,
			"websocket_url": None,
			"websocket_port": None
		}
	return Response(response_data)

def check_for_available_session():
	# 현재 활성화된 게임 세션을 찾는다
	available_session = GameSession.objects.filter(is_active=False).first()
	if available_session:
		# 세션이 있을 경우
		return {
			"session_id": available_session.session_id,
			"websocket_url": available_session.websocket_url,
			"websocket_port": available_session.websocket_port
		}
	else:
		# 세션이 없을 경우
		return None

def match(request):
	return render(request, 'transcendence/match.html')

def pingpong(request):
	return render(request, 'transcendence/pingpong.html')

class MatchHistoryView(APIView):
	def get(self, request, username):
		# 해당 유저가 player1 또는 player2로 참여한 모든 매치 조회
		player_matches = Match.objects.filter(player1=username) | Match.objects.filter(player2=username)

		# 해당 매치들이 포함된 모든 SessionHistory 조회
		session_history = SessionHistory.objects.filter(match__in=player_matches).distinct()

		# 직렬화하여 JSON 응답으로 반환
		serializer = SessionHistorySerializer(session_history, many=True)
		return Response(serializer, status=status.HTTP_200_OK)

mysite/ChitChat/templates/chat/chatPage.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .chat-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 10px;
        }

        .chat-header {
            text-align: center;
            background-color: #075e54;
            color: #fff;
            padding: 10px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .chat-header h1 {
            font-size: 24px;
        }

        .chat-logout {
            text-align: right;
            padding: 10px;
        }

        .chat-logout a {
            text-decoration: none;
            color: #075e54;
            font-weight: bold;
        }

        .chat-logout a:hover {
            text-decoration: underline;
        }

        .chat__item__container {
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 10px;
            height: 300px;
            max-height: 300px;
            /* Set a maximum height for the chat container */
            overflow-y: auto;
            /* Add a vertical scrollbar when needed */
        }

        .chat-input-container {
            display: flex;
            align-items: center;
        }

        #id_message_send_input {
            flex: 1;
            /* Take up available space */
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }

        #id_message_send_button {
            padding: 5px 10px;
            background-color: #075e54;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            margin-left: 10px;
        }

        .chat-message {
            background-color: #e4f9f5;
            border-radius: 10px;
            margin: 10px 0;
            padding: 10px;
            position: relative;
        }

        .chat-message.right {
                background-color: black;
            width: 80%;
            float: right;
            clear: both;
            margin-left: auto;
            margin-right: 0;
        }

        .chat-message.left {
            background-color: #075e54;
            width: 80%;
            float: left;
            clear: both;
            margin-left: 0;
            margin-right: auto;
        }

        .chat-message span {
            font-weight: bold;
            color: white;
        }

        .message-timestamp {
            font-size: 10px;
            position: absolute;
            top: 5px;
            right: 5px;
        }

        .message-username {
            font-size: 12px;
            position: absolute;
            bottom: 5px;
            right: 5px;
        }
    </style>
</head>

<body>
    <div class="chat-container">
        <div class="chat-header">
            <h1>Chit-Chat <i class="fas fa-comment"></i></h1>
        </div>
        <div class="chat-logout">
            {% if request.user.is_authenticated %}
                <div style="float: left; font-weight: bold; color: #036358;">{{ request.user|title }} </div>
                
                <!-- 로그아웃 폼 -->
                <div style="float: right;">
                    <form id="logout-form" action="{% url 'logout-user' %}" method="POST" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" style="background: none; border: none; padding: 0; cursor: pointer;">
                            <i class="fas fa-sign-out-alt"></i>
                        </button>
                    </form>
                </div>
        
                <div style="clear: both;"></div>
            {% endif %}
        </div>
        <div class="chat__item__container" id="id_chat_item_container">
            <!-- Messages will be displayed here with a scrollbar -->
        </div>
        <div class="chat-input-container">
            <input type="text" id="id_message_send_input" placeholder="Type your message..." />
            <button type="submit" id="id_message_send_button"><i class="fas fa-paper-plane"></i> Send</button>
        </div>
    </div>
    <script>
        const chatSocket = new WebSocket("ws://" + window.location.host + "/");
        chatSocket.onopen = function (e) {
            console.log("The connection was set up successfully!");
        };
        chatSocket.onclose = function (e) {
            console.log("Something unexpected happened!");
        };
        document.querySelector("#id_message_send_input").focus();
        document.querySelector("#id_message_send_input").onkeyup = function (e) {
            if (e.keyCode == 13) {
                document.querySelector("#id_message_send_button").click();
            }
        };
        document.querySelector("#id_message_send_button").onclick = function (e) {
            var messageInput = document.querySelector("#id_message_send_input").value;
            var currentTime = new Date();
            var time = currentTime.toLocaleTimeString();
            chatSocket.send(JSON.stringify({
                message: messageInput,
                username: "{{request.user.username}}",
                time: time
            }));
        };
        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            var messageContainer = document.querySelector("#id_chat_item_container");
            var div = document.createElement("div");
            div.className = (data.username === "{{request.user.username}}") ? "chat-message right" : "chat-message left";
            div.innerHTML = `<div class="message-content">
                <span class="message-username">${data.username.charAt(0).toUpperCase() + data.username.slice(1)}</span>
                <span class="message-text">${data.message}</span>
                <span class="message-timestamp">${data.time}</span>
            </div>`;
            document.querySelector("#id_message_send_input").value = "";
            messageContainer.appendChild(div);
            // Scroll to the bottom of the chat container
            messageContainer.scrollTop = messageContainer.scrollHeight;
        };
    </script>
</body>

</html>

mysite/ChitChat/templates/chat/loginPage.html
<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            width: 100vw;
            margin: 0;
        }

        form {
            max-width: 300px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            /* text-align: center; */
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .branding {
            margin-bottom: 20px;
            font-size: 24px;
            font-weight: bold;
            color: #128C7E;
            /* ChitChat brand color */
        }

        .btn-container {
            text-align: center;
        }

        button {
            background-color: #128C7E;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #075e54;
        }

        label {
            font-weight: bold;
            text-align: left;
            width: 85%;
        }

        input[type="text"],
        input[type="password"] {
            width: 80%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
    </style>
</head>

<body>
    <form method="post">
		<!-- django의 템플릿 태그로, 폼에 보안 토큰이 포함된 숨겨진 입력 필드를 삽입 -->
        {% csrf_token %}
        <div class="branding">Chit-Chat</div>
        {{form.as_p}}
        <div class="btn-container">
            <button type="submit">Login</button>
        </div>
    </form>
</body>

</html>

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/transcendence/templates/transcendence/match.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Match Making</title>
    <script>
        // Function to check for available sessions
        async function checkSession() {
            try {
                const response = await fetch("{% url 'pingpong:check-session' %}");
                const data = await response.json();

                if (data.session_id) {
                    // If a session is found, store session details and redirect to pingpong.html
                    sessionStorage.setItem('session_id', data.session_id);
                    sessionStorage.setItem('websocket_url', data.websocket_url);
                    sessionStorage.setItem('websocket_port', data.websocket_port);
                    window.location.href = "{% url 'pingpong:pingpong' %}";
                } else {
                    alert('No available session found.');
                }
            } catch (error) {
                console.error('Error checking session:', error);
                alert('Failed to check session.');
            }
        }
    </script>
</head>
<body>
    <h1>Match Making</h1>
    <button onclick="checkSession()">Check Available Session</button>
</body>
</html>

mysite/transcendence/templates/transcendence/pingpong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ping Pong Game</title>
    <style>
        /* 게임 패널의 스타일 */
        #game-panel {
            position: relative;
            width: 100px;
            height: 20px;
            background-color: blue;
            margin-top: 20px;
        }

        /* 패널을 움직일 수 있는 컨테이너 */
        #game-container {
            width: 100%;
            height: 100px;
            background-color: lightgrey;
            position: relative;
            overflow: hidden;
        }
    </style>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const session_id = sessionStorage.getItem('session_id');
            const websocket_url = sessionStorage.getItem('websocket_url');
            const websocket_port = sessionStorage.getItem('websocket_port');

            // JWT 토큰을 하드코딩으로 추가
            const jwt_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2VtYWlsIjoibWluamNob0BzdHVkZW50LjQyc2VvdWwua3IiLCJ1c2VybmFtZSI6Im1pbmpjaG8iLCJleHAiOjE3MjQ3MzIyOTZ9.9aQIUP8_2ySEIR_VRSZoJoMrSJiCDhBdstgdEo12fm4";

            // JWT 토큰 해석하여 username 추출
            function parseJwt(token) {
                const base64Url = token.split('.')[1];
                const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
                const jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
                    return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
                }).join(''));

                return JSON.parse(jsonPayload);
            }

            const decodedToken = parseJwt(jwt_token);
            const username = decodedToken.username;

            if (session_id && websocket_url && websocket_port && jwt_token) {

                console.log('Session ID:', session_id);
                console.log('WebSocket URL:', websocket_url);
                console.log('WebSocket Port:', websocket_port);
                console.log('Username:', username);

                const ws = new WebSocket(`ws://${websocket_url}:${websocket_port}/ws/game/${session_id}/?token=${jwt_token}`);

                ws.onopen = function() {
                    console.log('WebSocket connection established');
                };

                ws.onmessage = function(event) {
                    const data = JSON.parse(event.data);

                    if (data.type == "ping") {
                        ws.send(JSON.stringify({
                            type: "pong",
                            username: username
                        }));
                        console.log('Message from server:', data.type);
                        return;
                    }

                    console.log('Message from server:', data.message);

                    // 받은 메시지를 화면에 표시
                    const messageContainer = document.getElementById('message-container');
                    const messageElement = document.createElement('p');
                    messageElement.textContent = 'Message from server: ' + data.message;
                    messageContainer.appendChild(messageElement);
                };

                ws.onclose = function() {
                    console.log('WebSocket connection closed');
                };

                // 게임 패널을 움직이기 위한 코드
                const panel = document.getElementById('game-panel');
                let panelPosition = 0;
                const step = 10; // 패널이 움직이는 단위

                document.addEventListener('keydown', function(event) {
                    if (event.key === 'A' || event.key === 'a') {
                        // 'A' 키가 눌렸을 때 패널을 왼쪽으로 이동
                        if (panelPosition > 0) {
                            panelPosition -= step;
                            panel.style.left = panelPosition + 'px';
                        }
                        // 서버로 정보 전송
                        ws.send(JSON.stringify({username: username, action: "l", position: panelPosition}));
                    } else if (event.key === 'D' || event.key === 'd') {
                        // 'D' 키가 눌렸을 때 패널을 오른쪽으로 이동
                        if (panelPosition < document.getElementById('game-container').offsetWidth - panel.offsetWidth) {
                            panelPosition += step;
                            panel.style.left = panelPosition + 'px';
                        }
                        // 서버로 정보 전송
                        ws.send(JSON.stringify({username: username, action: "r", position: panelPosition}));
                    }
                });

            } else {
                alert('Session information is missing. Redirecting to match page.');
                window.location.href = "{% url 'pingpong:match' %}";
            }
        });
    </script>
</head>
<body>
    <h1>Ping Pong Game</h1>
    
    <!-- 게임 패널과 컨테이너 -->
    <div id="game-container">
        <div id="game-panel"></div>
    </div>

    <!-- 받은 메시지를 출력할 컨테이너 -->
    <div id="message-container"></div>
    
    <!-- 게임 관련 컨텐츠를 여기에 추가하세요 -->
</body>
</html>

mysite/transcendence/templates/transcendence/transcendencePage.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .chat-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 10px;
        }

        .chat-header {
            text-align: center;
            background-color: #075e54;
            color: #fff;
            padding: 10px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .chat-header h1 {
            font-size: 24px;
        }

        .chat-logout {
            text-align: right;
            padding: 10px;
        }

        .chat-logout a {
            text-decoration: none;
            color: #075e54;
            font-weight: bold;
        }

        .chat-logout a:hover {
            text-decoration: underline;
        }

        .chat__item__container {
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 10px;
            height: 300px;
            max-height: 300px;
            /* Set a maximum height for the chat container */
            overflow-y: auto;
            /* Add a vertical scrollbar when needed */
        }

        .chat-input-container {
            display: flex;
            align-items: center;
        }

        #id_message_send_input {
            flex: 1;
            /* Take up available space */
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 16px;
        }

        #id_message_send_button {
            padding: 5px 10px;
            background-color: #075e54;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            margin-left: 10px;
        }

        .chat-message {
            background-color: #e4f9f5;
            border-radius: 10px;
            margin: 10px 0;
            padding: 10px;
            position: relative;
        }

        .chat-message.right {
                background-color: black;
            width: 80%;
            float: right;
            clear: both;
            margin-left: auto;
            margin-right: 0;
        }

        .chat-message.left {
            background-color: #075e54;
            width: 80%;
            float: left;
            clear: both;
            margin-left: 0;
            margin-right: auto;
        }

        .chat-message span {
            font-weight: bold;
            color: white;
        }

        .message-timestamp {
            font-size: 10px;
            position: absolute;
            top: 5px;
            right: 5px;
        }

        .message-username {
            font-size: 12px;
            position: absolute;
            bottom: 5px;
            right: 5px;
        }
    </style>
</head>

<body>
    <div class="chat-container">
        <div class="chat-header">
            <h1>Ping-Pong <i class="fas fa-comment"></i></h1>
        </div>
        <div class="chat-logout">
            {% if request.user.is_authenticated %}
                <div style="float: left; font-weight: bold; color: #036358;">{{ request.user|title }} </div>
                
                <!-- 로그아웃 폼 -->
                <div style="float: right;">
                    <form id="logout-form" action="{% url 'pingpong:logout-user' %}" method="POST" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" style="background: none; border: none; padding: 0; cursor: pointer;">
                            <i class="fas fa-sign-out-alt"></i>
                        </button>
                    </form>
                </div>
        
                <div style="clear: both;"></div>
            {% endif %}
        </div>
        <div class="chat__item__container" id="id_chat_item_container">
            <!-- Messages will be displayed here with a scrollbar -->
        </div>
        <div class="chat-input-container">
            <input type="text" id="id_message_send_input" placeholder="Type your message..." />
            <button type="submit" id="id_message_send_button"><i class="fas fa-paper-plane"></i> Send</button>
        </div>
    </div>
    <script>
        const chatSocket = new WebSocket("ws://" + window.location.host + "/");
        chatSocket.onopen = function (e) {
            console.log("The connection was set up successfully!");
        };
        chatSocket.onclose = function (e) {
            console.log("Something unexpected happened!");
        };
        document.querySelector("#id_message_send_input").focus();
        document.querySelector("#id_message_send_input").onkeyup = function (e) {
            if (e.keyCode == 13) {
                document.querySelector("#id_message_send_button").click();
            }
        };
        document.querySelector("#id_message_send_button").onclick = function (e) {
            var messageInput = document.querySelector("#id_message_send_input").value;
            var currentTime = new Date();
            var time = currentTime.toLocaleTimeString();
            chatSocket.send(JSON.stringify({
                message: messageInput,
                username: "{{request.user.username}}",
                time: time
            }));
        };
        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);

            var messageContainer = document.querySelector("#id_chat_item_container");
            var div = document.createElement("div");
            div.className = (data.username === "{{request.user.username}}") ? "chat-message right" : "chat-message left";
            div.innerHTML = `<div class="message-content">
                <span class="message-username">${data.username.charAt(0).toUpperCase() + data.username.slice(1)}</span>
                <span class="message-text">${data.message}</span>
                <span class="message-timestamp">${data.time}</span>
            </div>`;
            document.querySelector("#id_message_send_input").value = "";
            messageContainer.appendChild(div);
            // Scroll to the bottom of the chat container
            messageContainer.scrollTop = messageContainer.scrollHeight;
        };
    </script>
</body>

</html>